/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fbf8fc",
        "surface-dim": "#dcd9dd",
        "surface-bright": "#fbf8fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f2f7",
        "surface-container": "#f0edf1",
        "surface-container-high": "#eae7eb",
        "surface-container-highest": "#e4e1e6",
        "on-surface": "#1b1b1e",
        "on-surface-variant": "#3f4753",
        "inverse-surface": "#303033",
        "inverse-on-surface": "#f3f0f4",
        outline: "#707884",
        "outline-variant": "#bfc7d5",
        "surface-tint": "#0061a5",
        primary: "#0061a5",
        "on-primary": "#ffffff",
        "primary-container": "#0d99ff",
        "on-primary-container": "#002f55",
        "inverse-primary": "#9fcaff",
        secondary: "#006c49",
        "on-secondary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        tertiary: "#5d3fe0",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9684ff",
        "on-tertiary-container": "#2c0096",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d2e4ff",
        "primary-fixed-dim": "#9fcaff",
        "on-primary-fixed": "#001c37",
        "on-primary-fixed-variant": "#00497e",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#e5deff",
        "tertiary-fixed-dim": "#c9bfff",
        "on-tertiary-fixed": "#1a0063",
        "on-tertiary-fixed-variant": "#441cc8",
        background: "#fbf8fc",
        "on-background": "#1b1b1e",
        "surface-variant": "#e4e1e6",
        "electric-violet": "#6366F1",
        "vivid-emerald": "#059669",
        "fresh-mint": "#34D399",
        "warm-amber": "#F59E0B",
        "danger-rose": "#F43F5E",
        "canvas-subtle": "#F9FAFB",
        "surface-border": "#E4E4E7",
        "surface-border-strong": "#18181B",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-mono-sm": ["'JetBrains Mono'", "monospace"],
        "label-pill": ["'Plus Jakarta Sans'", "sans-serif"],
        "action-button": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
